"""
    triangular_torus_bonds(Lx, Ly; shear=0)

Return the nearest-neighbor bonds of a triangular lattice represented on an
`Lx × Ly` square grid with PBC. The three (forward) bond directions are
(1, 0), (0, 1), (1, 1), so every undirected triangular-lattice bond appears
exactly once. Each element is a named tuple containing the wrapped `source`
and `target`, the `unwrapped_target`, the `direction` index, and the torus
`winding` in (Lx, Ly).

With `shear != 0`, the torus is generated by `T₁ = (Lx, 0)` and
`T₂ = (shear, Ly)`. Crossing the positive `y` boundary therefore shifts
the wrapped `x` coordinate by `-shear`.
"""
function triangular_torus_bonds(
    Lx::Integer,
    Ly::Integer;
    shear::Integer=0,
)
    Lx >= 3 || throw(ArgumentError("Lx must be at least 3 to avoid duplicate torus bonds"))
    Ly >= 3 || throw(ArgumentError("Ly must be at least 3 to avoid duplicate torus bonds"))

    directions = ((1, 0), (0, 1), (1, 1))
    bonds = NamedTuple[]
    sizehint!(bonds, 3 * Lx * Ly)

    for y in 1:Ly, x in 1:Lx
        for (direction, displacement) in enumerate(directions)
            dx, dy = displacement
            unwrapped_target = (x + dx, y + dy)
            winding_y = fld(unwrapped_target[2] - 1, Ly)
            wrapped_y = unwrapped_target[2] - winding_y * Ly
            shear_shifted_x = unwrapped_target[1] - winding_y * shear
            winding_x = fld(shear_shifted_x - 1, Lx)
            wrapped_x = shear_shifted_x - winding_x * Lx
            target = (wrapped_x, wrapped_y)
            winding = (winding_x, winding_y)
            push!(bonds, (;
                source=(x, y),
                target,
                unwrapped_target,
                displacement,
                direction,
                winding,
            ))
        end
    end

    return bonds
end

"""
    staggered_pi_flux_hoppings(Lx, Ly; amplitude=1.0)

Construct an `Lx × Ly × 3` hopping array for the triangular-lattice Dirac
spin-liquid ansatz with staggered `[0, π]` flux through the two triangles of
every square-grid plaquette. The direction index follows
`1 => (1, 0)`, `2 => (0, 1)`, and `3 => (1, 1)`.

The gauge choice is

```text
t₁(x,y) = (-1)^y amplitude,
t₂(x,y) =        amplitude,
t₃(x,y) = (-1)^y amplitude.
```

It gives zero flux around the oriented triangle
`(x,y) → (x+1,y) → (x+1,y+1) → (x,y)` and `π` flux around
`(x,y) → (x+1,y+1) → (x,y+1) → (x,y)`. Consequently, every
primitive rhombus has `π` flux. This gauge doubles the unit cell along `y`,
so `Ly` must be even on a torus.
"""
function staggered_pi_flux_hoppings(
    Lx::Integer,
    Ly::Integer;
    amplitude::Real=1.0,
)
    Lx >= 3 || throw(ArgumentError("Lx must be at least 3 to avoid duplicate torus bonds"))
    Ly >= 3 || throw(ArgumentError("Ly must be at least 3 to avoid duplicate torus bonds"))
    iseven(Ly) || throw(ArgumentError(
        "Ly must be even for the chosen staggered-[0, π] torus gauge",
    ))
    amplitude > 0 || throw(ArgumentError("amplitude must be positive"))

    hopping = fill(ComplexF64(amplitude), Lx, Ly, 3)
    for y in 1:Ly
        staggered_sign = isodd(y) ? -1.0 : 1.0
        hopping[:, y, 1] .*= staggered_sign
        hopping[:, y, 3] .*= staggered_sign
    end

    return hopping
end

_aux_triangular_hopping(hopping::Number, source, unwrapped_target, direction) = hopping # uniform hopping
_aux_triangular_hopping(hopping::AbstractArray, source, unwrapped_target, direction) =
    hopping[source[1], source[2], direction] # site-dependent hopping
_aux_triangular_hopping(hopping, source, unwrapped_target, direction) =
    hopping(source, unwrapped_target, direction) # fallback

_aux_triangular_field(::Nothing, site) = (0.0, 0.0, 0.0)
_aux_triangular_field(fields::AbstractArray, site) =
    (fields[site[1], site[2], 1], fields[site[1], site[2], 2], fields[site[1], site[2], 3])
_aux_triangular_field(fields, site) = fields(site)

_spinful_aux_index(x::Integer, y::Integer, spin::Integer, Lx::Integer) =
    2 * ((y - 1) * Lx + x - 1) + spin


"""
Construct the spinful one-particle matrix for the nearest-neighbor auxiliary
parton Hamiltonian on a triangular torus [arxiv:2607.14766],

H_aux = ∑_{<i,j>, σ} t_ij f^†_iσ f_jσ + h.c. + ∑_i M_i · S_i.


The triangular lattice is represented on a square grid using the forward bond
directions `(1, 0)`, `(0, 1)`, and `(1, 1)`. The returned matrix is a
`2LxLy × 2LxLy` `Hermitian` matrix with the interleaved basis
`(1↑, 1↓, 2↑, 2↓, ...)`.

# Keyword arguments

- `hopping`: The oriented hopping `t_ij`. It may be a scalar, an
  `Lx × Ly × 3` array, or a callable
  `hopping(source, unwrapped_target, direction)`. For a callable, `source` and
  `unwrapped_target` are `(x, y)` tuples and `direction` labels the three bond
  directions in the order listed above. The target is deliberately not wrapped
  before the callback, allowing it to assign the correct magnetic boundary
  phase on a torus.
- `fields`: The real auxiliary fields `M_i = (Mx, My, Mz)`. It may be `nothing`,
  an `Lx × Ly × 3` array, or a callable `fields((x, y))`.
- `shear`: Defines a tilted torus with translation vectors `T₁ = (Lx, 0)`
  and `T₂ = (shear, Ly)`. The default `shear=0` gives a rectangular torus.

The hopping amplitude is used with the sign supplied by the caller; this
function does not insert an additional conventional minus sign.
"""
function hamiltonian_aux_triangular_torus(
    Lx::Integer,
    Ly::Integer;
    hopping=1.0,
    fields=nothing,
    shear::Integer=0,
)
    if hopping isa AbstractArray
        size(hopping) == (Lx, Ly, 3) || throw(DimensionMismatch(
            "hopping must have size (Lx, Ly, 3) = ($(Lx), $(Ly), 3), got $(size(hopping))",
        ))
    end
    if fields isa AbstractArray
        size(fields) == (Lx, Ly, 3) || throw(DimensionMismatch(
            "fields must have size (Lx, Ly, 3) = ($(Lx), $(Ly), 3), got $(size(fields))",
        ))
    end

    N = Lx * Ly
    H = zeros(ComplexF64, 2N, 2N)

    for bond in triangular_torus_bonds(Lx, Ly; shear)
        t = ComplexF64(_aux_triangular_hopping(
            hopping,
            bond.source,
            bond.unwrapped_target,
            bond.direction,
        ))
        x, y = bond.source
        x2, y2 = bond.target

        for spin in 1:2
            i = _spinful_aux_index(x, y, spin, Lx)
            j = _spinful_aux_index(x2, y2, spin, Lx)
            H[i, j] += t
            H[j, i] += conj(t)
        end
    end

    for y in 1:Ly, x in 1:Lx
        Mx, My, Mz = _aux_triangular_field(fields, (x, y))
        up = _spinful_aux_index(x, y, 1, Lx)
        down = _spinful_aux_index(x, y, 2, Lx)

        # M · S = (1/2) M · σ in the (↑, ↓) basis.
        H[up, up] += Mz / 2
        H[down, down] -= Mz / 2
        H[up, down] += (Mx - im * My) / 2
        H[down, up] += (Mx + im * My) / 2
    end

    return Hermitian(H)
end

function hamiltonain_J1J2(J1, J2, Lx, Ly; operators=["X", "Y", "Z"])
    ham_J1J2 = OpSum()
    for i in 1:Lx, j in 1:Ly, t in operators
        # J1
        if j != Ly
            ham_J1J2 += (J1, t, (i,j), t, (i,j+1))
        end
        if i != Lx
            ham_J1J2 += (J1, t, (i,j), t, (i+1,j))
        end

        # J2
        if i != Lx && j != Ly
            ham_J1J2 += (J2, t, (i,j), t, (i+1,j+1))
            ham_J1J2 += (J2, t, (i+1,j), t, (i,j+1))
        end
    end
    return ham_J1J2
end


# Define Helper Functions for P Operators
function P_matrix(factor)
    # Create an 8-index tensor and fill specific indices with the factor.
    P = zeros(ComplexF64, 2, 2, 2, 2, 2, 2, 2, 2)
    for i1 in 1:2, i2 in 1:2, i3 in 1:2, i4 in 1:2
        P[i1, i2, i2, i3, i3, i4, i4, i1] = factor
    end
    return P
end

function P_operator(hilbert, spins; P=nothing, factor=1)
    # Generate the ITensor operator for a given set of spins.
    if P === nothing
        P = P_matrix(factor)
    end
    inds = [hilbert[s]' for s in spins]  # use prime on physical indices
    append!(inds, [hilbert[s] for s in spins])
    return ITensor(P, inds)
end

function add_P_operators!(ham_op, hilbert, Lx, Ly, factor)
    sites = Int[]
    for i in 1:(Lx-1)
        for j in 1:(Ly-1)
            # Define the sites of the plaquette
            push!(sites, i   + (j-1)*Lx)
            push!(sites, i+1 + (j-1)*Lx)
            push!(sites, i+1 + (j)*Lx)
            push!(sites, i   + (j)*Lx)
            # Create and add the operator
            P_op = P_operator(hilbert, sites; factor=factor)
            push!(ham_op.tensors, P_op)
            push!(ham_op.sites, copy(sites))
            empty!(sites)
        end
    end
end

function hamiltonain_CSL(hilbert, J1, J2, lambda; kwargs...)
    ham_J1J2 = hamiltonain_J1J2(J1/4, J2/4, size(hilbert)...; kwargs...)

    # Create the tensor operator for the Hamiltonian
    tn_sum = QuantumNaturalGradient.TensorOperatorSum(ham_J1J2, hilbert)
    
    # Add P operators with both positive and negative imaginary factors
    add_P_operators!(tn_sum, hilbert, size(hilbert)..., im * lambda)
    add_P_operators!(tn_sum, hilbert, size(hilbert)..., -im * lambda)
    return tn_sum
end

function hamiltonian_hubbard(t, U, Lx, Ly)
    ham_hubbard = ITensors.OpSum()

    for i in 1:Lx, j in 1:Ly
        if j < Ly
            if t != 0
                ham_hubbard .+= (-t, "Cdag", (i, j),   "C", (i, j+1))
                ham_hubbard .+= (-t, "Cdag", (i, j+1), "C", (i, j))
            end
            # V (n_i - 1/2)(n_j - 1/2), constant dropped
            ham_hubbard .+= ( U, "N", (i, j), "N", (i, j+1))
            ham_hubbard .+= (-U/2, "N", (i, j))
            ham_hubbard .+= (-U/2, "N", (i, j+1))
        end

        if i < Lx
            if t != 0
                ham_hubbard .+= (-t, "Cdag", (i, j),   "C", (i+1, j))
                ham_hubbard .+= (-t, "Cdag", (i+1, j), "C", (i, j))
            end
            # V (n_i - 1/2)(n_j - 1/2), constant dropped
            ham_hubbard .+= ( U, "N", (i, j), "N", (i+1, j))
            ham_hubbard .+= (-U/2, "N", (i, j))
            ham_hubbard .+= (-U/2, "N", (i+1, j))
        end

    end
    
    return ham_hubbard
end

# total number operator
function build_Ntot_op(Lx::Int, Ly::Int)
    Ntot_op = ITensors.OpSum()

    for i in 1:Lx, j in 1:Ly
        Ntot_op .+= (1.0, "N", (i, j))
    end

    return Ntot_op
end

# CDW order parameter M^2 = (1/N^2) sum_{a,b} (-1)^(x_a+y_a+x_b+y_b) n_a n_b
function build_M_cdw2_op(Lx::Int, Ly::Int)
    M2_op = ITensors.OpSum()

    sites = Tuple{Int,Int,Float64}[]

    for i in 1:Lx, j in 1:Ly
        push!(sites, (i, j, float((-1)^(i + j))))
    end

    # M^2 = sum_a n_a + 2 sum_{a<b} s_a s_b n_a n_b
    # because n_a^2 = n_a for fermion number operators.
    for a in eachindex(sites)
        i, j, s = sites[a]
        M2_op .+= (1.0, "N", (i, j))

        for b in a+1:length(sites)
            k, l, sp = sites[b]
            M2_op .+= (2.0 * s * sp, "N", (i, j), "N", (k, l))
        end
    end

    return M2_op
end

# average nearest-neighbor density-density correlation (1/Nb) sum_{<a,b>} n_a n_b
function build_nn_dd_corr_op(Lx::Int, Ly::Int)
    nn_op = ITensors.OpSum()
    Nb = Lx * (Ly - 1) + Ly * (Lx - 1)
    coeff = 1.0 / Nb

    for i in 1:Lx, j in 1:Ly
        if j < Ly
            nn_op .+= (coeff, "N", (i, j), "N", (i, j+1))
        end

        if i < Lx
            nn_op .+= (coeff, "N", (i, j), "N", (i+1, j))
        end
    end

    return nn_op
end
